/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#e2e2e2",
        "primary-container": "#0f172a",
        "surface": "#121414",
        "tertiary-container": "#390003",
        "on-secondary-container": "#5a4100",
        "surface-container-highest": "#333535",
        "on-surface-variant": "#c6c6cd",
        "surface-variant": "#333535",
        "inverse-on-surface": "#2f3131",
        "on-secondary": "#402d00",
        "on-tertiary-fixed": "#410004",
        "secondary": "#ffc640",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#68000a",
        "secondary-fixed-dim": "#f9bd22",
        "tertiary-fixed": "#ffdad7",
        "error-container": "#93000a",
        "surface-container-lowest": "#0c0f0f",
        "outline-variant": "#45464d",
        "surface-tint": "#bec6e0",
        "inverse-primary": "#565e74",
        "on-secondary-fixed": "#261a00",
        "tertiary-fixed-dim": "#ffb3ad",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-container": "#eb4141",
        "on-secondary-fixed-variant": "#5c4300",
        "error": "#ffb4ab",
        "on-primary": "#283044",
        "primary-fixed": "#dae2fd",
        "primary": "#bec6e0",
        "on-error": "#690005",
        "on-background": "#e2e2e2",
        "outline": "#909097",
        "surface-dim": "#121414",
        "on-primary-container": "#798098",
        "secondary-container": "#e3aa00",
        "surface-container-low": "#1a1c1c",
        "surface-bright": "#37393a",
        "inverse-surface": "#e2e2e2",
        "secondary-fixed": "#ffdf9f",
        "surface-container-high": "#282a2b",
        "on-primary-fixed": "#131b2e",
        "background": "#121414",
        "surface-container": "#1e2020",
        "tertiary": "#ffb3ad",
        "on-tertiary-fixed-variant": "#930013",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "section-gap": "120px",
        "container-max": "1440px",
        "margin-mobile": "20px",
        base: "8px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "label-bold": ["Montserrat", "sans-serif"],
        "headline-lg": ["Bebas Neue", "cursive"],
        "display-xl": ["Bebas Neue", "cursive"],
        "body-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Bebas Neue", "cursive"],
        "headline-lg-mobile": ["Bebas Neue", "cursive"],
        "body-md": ["Montserrat", "sans-serif"],
        caption: ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "label-bold": ["14px", { lineHeight: "100%", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg": ["64px", { lineHeight: "110%", letterSpacing: "0.04em", fontWeight: "400" }],
        "display-xl": ["96px", { lineHeight: "100%", letterSpacing: "0.02em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "160%", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "120%", fontWeight: "400" }],
        "headline-lg-mobile": ["40px", { lineHeight: "110%", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "160%", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "140%", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
